[project]
name = "ics.cobraOps"
readme = "README.md"
authors = [
  {name = "Javier Gracia Carpio", email = "jgracia@mpe.mpg.de"},
]
requires-python = ">=3.9"
description = "A pacakage that simulates the movements of cobras and calculates their possible collisions"
license = "GPL-3.0"
dependencies = [
  "numpy",
  "scipy",
  "matplotlib",
#  "ics.cobraCharmer",   # we probably need to specify a minimum version
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/Subaru-PFS/ics_cobraOps/"

[tool.setuptools]
packages = ["ics.cobraOps"]
package-dir = {"" = "python"}

[tool.setuptools.dynamic]
version = {attr = "ics.cobraOps.__version__"}
