function output = getTargetsFromTargetList(fieldnum)
% retrieves targets from TargetLists generated by
% generatecollidingtargets.

    files = sort(dir2cell('*.txt'));
    jj = 1;
    for f = files
        tgtlist = loadxyz(f{1});
        tgt(jj,1) = tgtlist.c(fieldnum);
        jj = jj + 1;
    end
    output = tgt;
    